name: Smoke Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}   # enables "Run workflow" button

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker versions
        run: |
          docker --version
          docker compose version

      - name: Build & start (core + widget) via compose
        run: docker compose up -d --build core widget

      - name: Wait for core health
        run: |
          for i in {1..90}; do
            if curl -fsS http://localhost:8123/health >/dev/null; then
              echo "Core is healthy"; exit 0
            fi
            echo "Waiting for core... ($i)"; sleep 1
          done
          echo "Core health failed"; docker compose ps; exit 1

      - name: Inline smoke test (no external script)
        run: |
          curl -fsS http://localhost:8123/health >/dev/null
          RESP="$(curl -fsS -X POST http://localhost:8123/v1/widget_text \
            -H 'Content-Type: application/json' \
            -d '{"query":"Current asthma in adults by sex in the latest year available"}')"
          echo "$RESP" | grep -q '"answer_text"'    || { echo "missing answer_text"; echo "$RESP"; exit 1; }
          echo "$RESP" | grep -q '"engine_version"' || { echo "missing engine_version"; echo "$RESP"; exit 1; }
          echo "Smoke test OK"

      - name: Compose logs (always)
        if: always()
        run: docker compose logs --no-color core widget || true

      - name: Compose down
        if: always()
        run: docker compose down -v
