name: Smoke Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show Docker versions
        run: |
          docker --version
          docker compose version

      - name: Build & start (core + widget) via compose
        run: docker compose up -d --build core widget

      - name: Wait for core health
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:8123/health >/dev/null; then
              echo "Core is healthy"; break
            fi
            echo "Waiting for core... ($i)"
            sleep 1
          done
          curl -fsS http://localhost:8123/health

      - name: Run smoke test
        run: |
          chmod +x scripts/smoke_test.sh
          CORE_BASE_URL="http://localhost:8123" ./scripts/smoke_test.sh

      - name: Compose logs (always)
        if: always()
        run: docker compose logs --no-color core widget || true

      - name: Compose down
        if: always()
        run: docker compose down -v
